
import { Game, Review, User } from './types';

export const MOCK_GAMES: Game[] = [
  { id: 'p1', title: 'Counter-Strike 2', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/730/header.jpg', rating: 4.8, releaseDate: '2023-09-27', genre: ['Action', 'Shooter', 'Tactical'], platform: ['PC'], description: 'For over two decades, Counter-Strike has offered an elite competitive experience.', developer: 'Valve', timePlayed: '450h', trophiesCount: 1, totalTrophies: 1 },
  { id: 'p2', title: 'PUBG: BATTLEGROUNDS', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/578080/header.jpg', rating: 4.5, releaseDate: '2017-12-21', genre: ['Action', 'Shooter', 'Survival'], platform: ['PC', 'PS5', 'Xbox'], description: 'Land, loot and outwit your opponents to become the last player standing in a thrilling battle royale.', developer: 'KRAFTON, Inc.', timePlayed: '120h', trophiesCount: 30, totalTrophies: 39, kdRatio: 4.2 },
  { id: 'p3', title: 'Dota 2', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/570/header.jpg', rating: 4.7, releaseDate: '2013-07-09', genre: ['Strategy', 'MOBA'], platform: ['PC'], description: 'Every day, millions of players worldwide enter battle as one of over a hundred Dota heroes.', developer: 'Valve', timePlayed: '950h', trophiesCount: 0, totalTrophies: 0 },
  { id: 'p4', title: 'Banana', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2923300/header.jpg', rating: 4.1, releaseDate: '2024-04-23', genre: ['Casual', 'Clicker'], platform: ['PC'], description: 'Banana is a clicker game where you click a Banana to get more Bananas.', developer: 'Sky', kdRatio: 0.1 },
  { id: 'p5', title: 'Apex Legends', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1172470/header.jpg', rating: 4.6, releaseDate: '2020-11-04', genre: ['Action', 'Shooter', 'Battle Royale'], platform: ['PC', 'PS5', 'Xbox', 'Switch'], description: 'Conquer with character in Apex Legends, a free-to-play Hero Shooter game where legendary characters battle for glory.', developer: 'Respawn Entertainment' },
  { id: 'p6', title: 'Grand Theft Auto V', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/271590/header.jpg', rating: 4.9, releaseDate: '2015-04-14', genre: ['Action', 'Adventure', 'Open World'], platform: ['PC', 'PS5', 'Xbox'], description: 'When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled...', developer: 'Rockstar Games', kdRatio: 1.15 },
  { id: 'p7', title: 'Naraka: Bladepoint', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1203220/header.jpg', rating: 4.5, releaseDate: '2021-08-11', genre: ['Action', 'Battle Royale'], platform: ['PC', 'PS5', 'Xbox'], description: 'Dive into the legends of the Far East in NARAKA: BLADEPOINT; team up with friends in fast-paced melee fights.', developer: '24 Entertainment' },
  { id: 'p8', title: 'Once Human', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2139460/header.jpg', rating: 4.4, releaseDate: '2024-07-09', genre: ['Action', 'Survival', 'Open World'], platform: ['PC'], description: 'Once Human is a multiplayer open-world survival game set in a strange, post-apocalyptic future.', developer: 'Starry Studio' },
  { id: 'p9', title: 'Elden Ring', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1245620/header.jpg', rating: 5.0, releaseDate: '2022-02-25', genre: ['Action RPG', 'Open World'], platform: ['PC', 'PS5', 'Xbox'], description: 'Rise, Tarnished, and be guided by grace.', developer: 'FromSoftware' },
  { id: 'p10', title: 'Baldur\'s Gate 3', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1086940/header.jpg', rating: 5.0, releaseDate: '2023-08-03', genre: ['RPG', 'Adventure'], platform: ['PC', 'PS5', 'Xbox'], description: 'Gather your party and return to the Forgotten Realms.', developer: 'Larian Studios' },
  { id: 'p11', title: 'Rust', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/252490/header.jpg', rating: 4.6, releaseDate: '2018-02-08', genre: ['Action', 'Survival'], platform: ['PC', 'PS4', 'Xbox'], description: 'The only aim concerning Rust is to survive - Overcome struggles such as hunger, thirst and the cold.', developer: 'Facepunch Studios' },
  { id: 'p12', title: 'Team Fortress 2', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/440/header.jpg', rating: 4.7, releaseDate: '2007-10-10', genre: ['Action', 'Shooter'], platform: ['PC'], description: 'One of the most popular online action games of all time, Team Fortress 2 delivers constant free updates.', developer: 'Valve' },
  { id: 'p13', title: 'Starfield', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1716740/header.jpg', rating: 3.8, releaseDate: '2023-09-06', genre: ['RPG', 'Adventure'], platform: ['PC', 'Xbox'], description: 'The first new universe in 25 years from Bethesda.', developer: 'Bethesda' },
  { id: 'p14', title: 'Hades II', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1145350/header.jpg', rating: 4.9, releaseDate: '2024-05-06', genre: ['Roguelike'], platform: ['PC'], description: 'Battle beyond the Underworld.', developer: 'Supergiant Games' },
  { id: 'p15', title: 'Resident Evil 4', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2050650/header.jpg', rating: 4.9, releaseDate: '2023-03-24', genre: ['Action', 'Horror'], platform: ['PC', 'PS5', 'Xbox'], description: 'Survival is just the beginning.', developer: 'CAPCOM' },
  { id: 'p16', title: 'Stray', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1332010/header.jpg', rating: 4.6, releaseDate: '2022-07-19', genre: ['Adventure'], platform: ['PC', 'PS5'], description: 'Lost, alone and separated from family, a stray cat.', developer: 'BlueTwelve Studio' },
  { id: 'p17', title: 'Armored Core VI', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1888140/header.jpg', rating: 4.8, releaseDate: '2023-08-25', genre: ['Action'], platform: ['PC', 'PS5', 'Xbox'], description: 'FIRES OF RUBICON.', developer: 'FromSoftware' },
  { id: 'p18', title: 'Lies of P', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1627720/header.jpg', rating: 4.7, releaseDate: '2023-09-18', genre: ['Souls-like', 'RPG'], platform: ['PC', 'PS5', 'Xbox'], description: 'You are a puppet created by Geppetto.', developer: 'NEOWIZ' },
  { id: 'p19', title: 'Dead Space', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1693980/header.jpg', rating: 4.8, releaseDate: '2023-01-27', genre: ['Horror', 'Shooter'], platform: ['PC', 'PS5', 'Xbox'], description: 'Sci-fi survival horror classic.', developer: 'Motive' },
  { id: 'p20', title: 'Sea of Stars', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1244090/header.jpg', rating: 4.8, releaseDate: '2023-08-29', genre: ['RPG'], platform: ['PC', 'Switch', 'PS5'], description: 'A turn-based RPG inspired by the classics.', developer: 'Sabotage Studio' },
  { id: 'p21', title: 'Alan Wake 2', coverUrl: 'https://m.media-amazon.com/images/I/71uB7tO-mQL._AC_SL1500_.jpg', rating: 4.9, releaseDate: '2023-10-27', genre: ['Horror', 'Adventure'], platform: ['PC', 'PS5', 'Xbox'], description: 'A ritualistic murder spree threatens Bright Falls.', developer: 'Remedy Entertainment' },
  { id: 'p22', title: 'Hogwarts Legacy', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/990080/header.jpg', rating: 4.5, releaseDate: '2023-02-10', genre: ['RPG', 'Open World'], platform: ['PC', 'PS5', 'Xbox'], description: 'Experience Hogwarts in the 1800s.', developer: 'Avalanche Software' },
  { id: 'extra-1', title: 'Battlefield 2042', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1517290/header.jpg', rating: 3.2, releaseDate: '2021-11-19', genre: ['Shooter', 'Action'], platform: ['PC', 'PS5', 'Xbox'], description: 'Experience all-out warfare in the near future.', developer: 'DICE' },
  { id: 'extra-2', title: 'Fortnite', coverUrl: 'https://gmedia.playstation.com/is/image/psgv2/fortnite-listing-thumb-en-14nov22?$facebook$', rating: 4.5, releaseDate: '2017-07-25', genre: ['Shooter', 'Action'], platform: ['PC', 'PS5', 'Xbox', 'Switch', 'Mobile'], description: 'The premier battle royale experience.', developer: 'Epic Games' },
  { id: 'extra-3', title: 'Hunt: Showdown 1896', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/594650/header.jpg', rating: 4.6, releaseDate: '2019-08-27', genre: ['Shooter', 'Horror'], platform: ['PC', 'PS5', 'Xbox'], description: 'Bounty hunting in the Louisiana bayou.', developer: 'Crytek' },
  { id: 'extra-4', title: 'Crime Scene Cleaner', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1040200/header.jpg', rating: 4.8, releaseDate: '2024-08-14', genre: ['Simulation'], platform: ['PC'], description: 'Clean up after the mob to save your family.', developer: 'President Studio' },
  { id: 'extra-5', title: 'Chivalry 2', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1824220/header.jpg', rating: 4.4, releaseDate: '2022-06-12', genre: ['Action', 'Fighting'], platform: ['PC', 'PS5', 'Xbox'], description: 'Epic medieval movie-inspired battles.', developer: 'Torn Banner Studios' },
  { id: 'extra-6', title: 'Roblox', coverUrl: 'https://gmedia.playstation.com/is/image/psgv2/roblox-listing-thumb-01-en-12sep23?$facebook$', rating: 4.0, releaseDate: '2006-09-01', genre: ['Sandbox'], platform: ['PC', 'Xbox', 'Mobile'], description: 'Create and play millions of experiences.', developer: 'Roblox Corporation' },
  { id: 'extra-7', title: 'Star Wars Battlefront II', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1237950/header.jpg', rating: 4.3, releaseDate: '2017-11-17', genre: ['Shooter', 'Action'], platform: ['PC', 'PS4', 'Xbox'], description: 'Master your hero\'s journey in the Star Wars galaxy.', developer: 'DICE' },
  { id: 'extra-8', title: 'Star Wars Battlefront', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2854350/header.jpg', rating: 3.8, releaseDate: '2015-11-17', genre: ['Shooter', 'Action'], platform: ['PC', 'PS4', 'Xbox'], description: 'Live out your Star Wars battle fantasies.', developer: 'DICE' },
  { id: 'extra-9', title: 'Minecraft', coverUrl: 'https://m.media-amazon.com/images/I/61M6CInU8XL._SL1000_.jpg', rating: 5.0, releaseDate: '2011-11-18', genre: ['Sandbox', 'Adventure'], platform: ['PC', 'PS4', 'Xbox', 'Switch', 'Mobile'], description: 'Build anything your imagination can conceive.', developer: 'Mojang' },
  { id: 'extra-10', title: 'Far Cry 3', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/220240/header.jpg', rating: 4.9, releaseDate: '2012-11-29', genre: ['Shooter', 'Adventure'], platform: ['PC', 'PS4', 'Xbox'], description: 'Face insanity in an island paradise.', developer: 'Ubisoft' },
  { id: 'extra-11', title: 'skate.', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1903000/header.jpg', rating: 4.2, releaseDate: '2025-01-01', genre: ['Simulation', 'Sports'], platform: ['PC', 'PS5', 'Xbox'], description: 'The next evolution of skating.', developer: 'Full Circle' },
  { id: 'extra-12', title: 'The Finals', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2073850/header.jpg', rating: 4.5, releaseDate: '2023-12-07', genre: ['Shooter', 'Action'], platform: ['PC', 'PS5', 'Xbox'], description: 'Join the world\'s greatest game show.', developer: 'Embark Studios' },
  { id: 'extra-13', title: 'Call of Duty: Black Ops 6', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2933620/header.jpg', rating: 4.4, releaseDate: '2024-10-25', genre: ['Shooter', 'Action'], platform: ['PC', 'PS5', 'Xbox'], description: 'The next chapter in the legendary franchise.', developer: 'Treyarch' },
  { id: 'extra-14', title: 'Ghost Recon Breakpoint', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2231380/header.jpg', rating: 3.5, releaseDate: '2019-10-04', genre: ['Shooter', 'Action'], platform: ['PC', 'PS4', 'Xbox'], description: 'Survive behind enemy lines as a Ghost.', developer: 'Ubisoft' },
  { id: 'extra-15', title: 'Far Cry 6', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1966720/header.jpg', rating: 3.9, releaseDate: '2021-10-07', genre: ['Shooter', 'Action'], platform: ['PC', 'PS5', 'Xbox'], description: 'Welcome to Yara, a tropical paradise frozen in time.', developer: 'Ubisoft' },
  { id: 'extra-16', title: 'Batman: Arkham Knight', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/208650/header.jpg', rating: 4.8, releaseDate: '2015-06-23', genre: ['Action', 'Adventure'], platform: ['PC', 'PS4', 'Xbox'], description: 'The final chapter in the Arkham trilogy.', developer: 'Rocksteady' },
  { id: 'extra-17', title: 'Batman: Arkham City', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/200260/header.jpg', rating: 4.9, releaseDate: '2011-10-18', genre: ['Action', 'Adventure'], platform: ['PC', 'PS4', 'Xbox'], description: 'Explore the prison city of Gotham.', developer: 'Rocksteady' },
  { id: 'extra-18', title: 'Batman: Arkham Asylum', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/35140/header.jpg', rating: 4.8, releaseDate: '2009-08-25', genre: ['Action', 'Adventure'], platform: ['PC', 'PS4', 'Xbox'], description: 'Return to the asylum.', developer: 'Rocksteady' },
  { id: 'extra-19', title: 'Gears of War 3', coverUrl: 'https://m.media-amazon.com/images/I/51f8pxt4fGL.jpg', rating: 4.7, releaseDate: '2011-09-20', genre: ['Shooter', 'Action'], platform: ['Xbox'], description: 'The final struggle for humanity.', developer: 'Epic Games' },
  { id: 'extra-20', title: 'Gears of War', coverUrl: 'https://m.media-amazon.com/images/I/514N8CYD4NL.jpg', rating: 4.8, releaseDate: '2006-11-07', genre: ['Shooter', 'Action'], platform: ['PC', 'Xbox'], description: 'The legendary cover-based shooter.', developer: 'Epic Games' },
  { id: 'extra-21', title: 'Gears of War: Ultimate Edition', coverUrl: 'https://m.media-amazon.com/images/I/81vH4fA-0XL._AC_SL1500_.jpg', rating: 4.5, releaseDate: '2015-08-25', genre: ['Shooter', 'Action'], platform: ['PC', 'Xbox'], description: 'Remastered for a new generation.', developer: 'The Coalition' },
  { id: 'extra-22', title: 'Gears of War 2', coverUrl: 'https://m.media-amazon.com/images/I/51PCEz1eKFL.jpg', rating: 4.8, releaseDate: '2008-11-07', genre: ['Shooter', 'Action'], platform: ['Xbox'], description: 'Bigger, better, and more intense.', developer: 'Epic Games' },
  { id: 'extra-23', title: 'Gears of War 4', coverUrl: 'https://m.media-amazon.com/images/I/91tK39f0LdL._AC_SL1500_.jpg', rating: 4.2, releaseDate: '2016-10-11', genre: ['Shooter', 'Action'], platform: ['PC', 'Xbox'], description: 'A new saga begins.', developer: 'The Coalition' },
  { id: 'extra-24', title: 'Gears 5', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1097840/header.jpg', rating: 4.4, releaseDate: '2019-09-10', genre: ['Shooter', 'Action'], platform: ['PC', 'Xbox'], description: 'Discover your connection to the enemy.', developer: 'The Coalition' },
  { id: 'extra-25', title: 'Forza Horizon', coverUrl: 'https://m.media-amazon.com/images/I/81KjL7N5kLL._AC_SL1500_.jpg', rating: 4.8, releaseDate: '2012-10-23', genre: ['Racing'], platform: ['Xbox'], description: 'Where cars and music collide.', developer: 'Playground Games' },
  { id: 'extra-26', title: 'Forza Horizon 2', coverUrl: 'https://m.media-amazon.com/images/I/81C65Rz9mLL._AC_SL1500_.jpg', rating: 4.7, releaseDate: '2014-09-30', genre: ['Racing'], platform: ['Xbox'], description: 'Race through southern Europe.', developer: 'Playground Games' },
  { id: 'extra-27', title: 'Forza Horizon 3', coverUrl: 'https://m.media-amazon.com/images/I/81U2fWpndmL._AC_SL1500_.jpg', rating: 4.8, releaseDate: '2016-09-27', genre: ['Racing'], platform: ['PC', 'Xbox'], description: 'The Horizon festival heads to Australia.', developer: 'Playground Games' },
  { id: 'extra-28', title: 'Forza Horizon 4', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1293830/header.jpg', rating: 4.9, releaseDate: '2018-10-02', genre: ['Racing'], platform: ['PC', 'Xbox'], description: 'Seasons change everything in Great Britain.', developer: 'Playground Games' },
  { id: 'extra-29', title: 'Forza Horizon 5', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1551360/header.jpg', rating: 4.9, releaseDate: '2021-11-09', genre: ['Racing'], platform: ['PC', 'PS5', 'Xbox'], description: 'Explore the vibrant landscapes of Mexico.', developer: 'Playground Games' },
  { id: 'extra-30', title: 'Assassin\'s Creed IV Black Flag', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/242050/header.jpg', rating: 4.9, releaseDate: '2013-10-29', genre: ['Action', 'Adventure'], platform: ['PC', 'PS4', 'Xbox'], description: 'Become a pirate assassin in the Golden Age of Piracy.', developer: 'Ubisoft' },
  { id: 'extra-31', title: 'State of Decay 2', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/495420/header.jpg', rating: 4.2, releaseDate: '2018-05-22', genre: ['Action', 'Survival'], platform: ['PC', 'Xbox'], description: 'Build a community and survive the apocalypse.', developer: 'Undead Labs' },
  { id: 'extra-32', title: 'The Evil Within', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/268050/header.jpg', rating: 4.4, releaseDate: '2014-10-14', genre: ['Horror', 'Action'], platform: ['PC', 'PS4', 'Xbox'], description: 'Face your fears in this psychological horror.', developer: 'Tango Gameworks' },
  { id: 'extra-33', title: 'Far Cry 4', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/298110/header.jpg', rating: 4.7, releaseDate: '2014-11-18', genre: ['Shooter', 'Adventure'], platform: ['PC', 'PS4', 'Xbox'], description: 'Overthrow a dictator in the Himalayas.', developer: 'Ubisoft' },
  { id: 'extra-34', title: 'Halo Infinite', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1240440/header.jpg', rating: 4.3, releaseDate: '2021-12-08', genre: ['Shooter', 'Action'], platform: ['PC', 'Xbox'], description: 'Become the Master Chief and save humanity.', developer: '343 Industries' },
  { id: 'extra-35', title: 'Marvel Rivals', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2760740/header.jpg', rating: 4.5, releaseDate: '2024-12-01', genre: ['Shooter', 'Action'], platform: ['PC', 'PS5', 'Xbox'], description: 'Team-based superhero PvP action.', developer: 'NetEase Games' },
  { id: 'extra-36', title: 'Far Cry 5', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/552520/header.jpg', rating: 4.6, releaseDate: '2018-03-27', genre: ['Shooter', 'Action'], platform: ['PC', 'PS4', 'Xbox'], description: 'Face a cult in the heart of Montana.', developer: 'Ubisoft' },
  { id: 'extra-37', title: 'Call of Duty: Warzone', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1962660/header.jpg', rating: 4.1, releaseDate: '2020-03-10', genre: ['Shooter', 'Action', 'Battle Royale'], platform: ['PC', 'PS5', 'Xbox'], description: 'Welcome to Warzone, the massive free-to-play combat arena which features Battle Royales.', developer: 'Infinity Ward' },
  { id: 'extra-38', title: 'EA Sports FC 26', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2592390/header.jpg', rating: 3.8, releaseDate: '2025-09-26', genre: ['Sports', 'Simulation'], platform: ['PC', 'PS5', 'Xbox', 'Switch'], description: 'The next generation of the world\'s game, introducing upgraded authentic tactical simulation.', developer: 'EA Vancouver' },
  { id: 'extra-39', title: 'Valorant', coverUrl: 'https://media.rawg.io/media/screenshots/003/0034a179ee42b3be9fb32c4b574f1cf8.jpg', rating: 4.4, releaseDate: '2020-06-02', genre: ['Shooter', 'Action', 'Tactical'], platform: ['PC', 'PS5', 'Xbox'], description: 'Character-based 5v5 tactical shooter where precise gunplay meets unique agent abilities.', developer: 'Riot Games' },
  { id: 'extra-lol', title: 'League of Legends', coverUrl: 'https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/blt4f49439a3f2824fe/6346bc063d83b05786ed057e/League_of_Legends_Logo_Artwork.jpg', rating: 4.4, releaseDate: '2009-10-27', genre: ['Strategy', 'MOBA', 'Multiplayer'], platform: ['PC'], description: 'Team up with friends in this premier 5v5 MOBA of strategic tactics and legendary battles.', developer: 'Riot Games' },
  { id: 'extra-sims4', title: 'The Sims 4', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1222670/library_600x900.jpg', rating: 4.3, releaseDate: '2014-09-02', genre: ['Simulation', 'Casual'], platform: ['PC', 'PS4', 'Xbox'], description: 'Unleash your imagination and create a unique world of Sims that’s an expression of you!', developer: 'Maxis' },
  { id: 'extra-rocketleague', title: 'Rocket League', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/252950/library_600x900.jpg', rating: 4.6, releaseDate: '2015-07-07', genre: ['Sports', 'Action'], platform: ['PC', 'PS4', 'Xbox', 'Switch'], description: 'Soccer meets driving in this high-powered hybrid of arcade-style soccer and vehicular mayhem!', developer: 'Psyonix LLC' },
  { id: 'extra-overwatch', title: 'Overwatch', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2357570/library_600x900.jpg', rating: 4.0, releaseDate: '2022-10-04', genre: ['Shooter', 'Action', 'Multiplayer'], platform: ['PC', 'PS5', 'Xbox', 'Switch'], description: 'A team-based hero shooter set in an optimistic future, featuring epic squad battlegrounds.', developer: 'Blizzard Entertainment' },
  { id: 'extra-diablo4', title: 'Diablo IV', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2344520/library_600x900.jpg', rating: 4.1, releaseDate: '2023-06-05', genre: ['Action RPG', 'RPG', 'Hack & Slash'], platform: ['PC', 'PS5', 'Xbox'], description: 'The legendary action RPG returns with an endless evil to slaughter, countless abilities to master, and nightmarish dungeons.', developer: 'Blizzard Entertainment' },
  { id: 'extra-forza6', title: 'Forza Horizon 6', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1551360/library_600x900.jpg', rating: 4.8, releaseDate: '2026-09-30', genre: ['Racing', 'Simulation', 'Sports'], platform: ['PC', 'Xbox'], description: 'The upcoming masterpiece of open-world racing, introducing state-of-the-art dynamic simulation environments.', developer: 'Playground Games' },
  { id: 'extra-repo', title: 'R.E.P.O.', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3211510/library_600x900.jpg', rating: 4.5, releaseDate: '2024-11-20', genre: ['Action', 'Horror', 'Tactical'], platform: ['PC'], description: 'A co-op extraction horror game where you infiltrate abandoned space objects and recover valuable salvage under pressure.', developer: 'N/A' },
  { id: 'extra-wow', title: 'World of Warcraft', coverUrl: 'https://media.rawg.io/media/games/18a/18a0ffbe97ccda7be34df4e28080b0bb.jpg', rating: 4.8, releaseDate: '2004-11-23', genre: ['RPG', 'MMORPG'], platform: ['PC'], description: 'Join thousands of mighty heroes in a world of myth, magic, and legendary adventure.', developer: 'Blizzard Entertainment' },
  { id: 'extra-slaythespire2', title: 'Slay the Spire 2', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2868470/library_600x900.jpg', rating: 4.9, releaseDate: '2025-12-15', genre: ['Card Game', 'Roguelike', 'Strategy'], platform: ['PC'], description: 'The highly anticipated sequel to the pioneer deck-building roguelike. Draft powerful decks and climb the Spire.', developer: 'Mega Crit' },
  { id: 'extra-battlefield6', title: 'Battlefield 6', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1517290/library_600x900.jpg', rating: 4.2, releaseDate: '2026-10-24', genre: ['Action', 'Shooter', 'Tactical'], platform: ['PC', 'PS5', 'Xbox'], description: 'The upcoming installment of the massive scale military shooter from EA and DICE, taking combat to new bounds.', developer: 'DICE' },
  { id: 'extra-rainbowsix', title: 'Tom Clancy\'s Rainbow Six Siege', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/359550/library_600x900.jpg', rating: 4.7, releaseDate: '2015-12-01', genre: ['Shooter', 'Action', 'Tactical'], platform: ['PC', 'PS5', 'Xbox'], description: 'Master the art of destruction and gadgetry in intense close-quarters combat and team-based tactical gameplay.', developer: 'Ubisoft' }
];

export const WAITED_2026_GAMES: Game[] = [
  { id: 'w1', title: 'GTA VI', coverUrl: 'https://media-rockstargames-com.akamaized.net/rockstargames-newsite/img/global/games/fob/640/GTAVI.jpg', rating: 5.0, releaseDate: '2025-11-01', genre: ['Action', 'Open World'], platform: ['PS5', 'Xbox'], description: 'Welcome back to Vice City. Step into the sprawling streets of Leonida in absolute next-gen scale.', developer: 'Rockstar Games' },
  { id: 'w2', title: 'Ghost of Yōtei', coverUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?q=80&w=600&h=800&auto=format&fit=crop', rating: 4.9, releaseDate: '2025-10-31', genre: ['Action', 'Adventure'], platform: ['PS5'], description: 'A new warrior named Atsu rises from the ashes. Explore the breathtaking lands surrounding Mount Yōtei.', developer: 'Sucker Punch Productions' },
  { id: 'w3', title: 'Monster Hunter Wilds', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2246340/header.jpg', rating: 4.8, releaseDate: '2025-02-28', genre: ['Action', 'RPG'], platform: ['PC', 'PS5', 'Xbox'], description: 'The next evolution of raw monster hunting. Survive dynamic climates and track colossal beasts.', developer: 'Capcom' },
  { id: 'w4', title: 'Silksong', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1030300/header.jpg', rating: 4.9, releaseDate: '2026-01-01', genre: ['Metroidvania'], platform: ['PC', 'Switch'], description: 'Play as Hornet, princess-protector of Hallownest, embarking on a lethal pilgrimage through a new kingdom.', developer: 'Team Cherry' },
  { id: 'w5', title: 'Doom: The Dark Ages', coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2744300/header.jpg', rating: 4.8, releaseDate: '2025-06-01', genre: ['Shooter', 'Action'], platform: ['PC', 'PS5', 'Xbox'], description: 'The cinematic prequel telling the medieval origin of the Doom Slayer. Rip and tear with shields and dragons.', developer: 'id Software' },
  { id: 'w6', title: 'Metroid Prime 4: Beyond', coverUrl: 'https://m.media-amazon.com/images/I/81S6-0uWnFL._AC_SL1500_.jpg', rating: 4.7, releaseDate: '2025-09-15', genre: ['Adventure', 'Shooter'], platform: ['Switch'], description: 'Samus Aran returns. Embark on a new cosmic bounty hunt across uncharted stellar frontiers.', developer: 'Retro Studios' },
  { id: 'w7', title: 'TES VI', coverUrl: 'https://m.media-amazon.com/images/I/81rE92M-dtL._AC_SL1500_.jpg', rating: 4.9, releaseDate: '2026-11-11', genre: ['RPG'], platform: ['PC', 'Xbox'], description: 'Legendary Elder Scrolls series from Bethesda Game Studios.', developer: 'Bethesda' },
  { id: 'w8', title: 'Death Stranding 2', coverUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=600&h=800&auto=format&fit=crop', rating: 4.7, releaseDate: '2026-04-15', genre: ['Adventure', 'Sci-Fi'], platform: ['PS5'], description: 'Hideo Kojima’s next masterpiece. Reconnect the fractured world as Sam Porter Bridges once more.', developer: 'Kojima Productions' },
  { id: 'w9', title: 'Fable', coverUrl: 'https://images.unsplash.com/photo-1519074069444-1ba4e5663aa4?q=80&w=600&h=800&auto=format&fit=crop', rating: 4.6, releaseDate: '2025-11-20', genre: ['RPG', 'Adventure'], platform: ['PC', 'Xbox'], description: 'Welcome back to Albion. A fantastical land of heroes, whimsy, and dangerous fairy tales.', developer: 'Playground Games' }
];

export const CURRENT_USER: User = {
  id: 'user-1',
  name: 'PIRIUX',
  handle: '@piriux',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=200&h=200&auto=format&fit=crop',
  coverUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop',
  bio: 'Just a casual gamer exploring vast worlds and sharing my thoughts one level at a time.',
  stats: { reviews: 42, followers: 3, following: 2, gamesPlayed: 156 },
  journyx: ['p1', 'p2', 'p10'],
  followersList: [
    { id: 'user-2', name: 'ViperNeon_X', handle: '@viperneon_x', avatar: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=150&h=150&fit=crop' },
    { id: 'user-3', name: 'AstroViking_TV', handle: '@astroviking_tv', avatar: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?q=80&w=150&h=150&fit=crop' },
    { id: 'user-4', name: 'PixelHunter_99', handle: '@pixelhunter_99', avatar: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=150&h=150&fit=crop' }
  ],
  followingList: [
    { id: 'user-5', name: 'FragLord_zZ', handle: '@fraglord_zz', avatar: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?q=80&w=150&h=150&fit=crop' },
    { id: 'user-6', name: 'Valkyrie_Rage', handle: '@valkyrie_rage', avatar: 'https://images.unsplash.com/photo-1614036417651-efe5912149d8?q=80&w=150&h=150&fit=crop' }
  ],
  linkedProfiles: [
    { platform: 'playstation', username: 'Piriux_PSN', connected: true },
    { platform: 'pc', username: 'piriux_steam', connected: true },
    { platform: 'xbox', username: '', connected: false },
    { platform: 'nintendo', username: '', connected: false },
  ]
};

export const MOCK_REVIEWS: Review[] = [
  { id: 'r1', gameId: 'p1', userId: 'user-2', userName: 'ViperNeon_X', userAvatar: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=150&h=150&fit=crop', rating: 5, content: "Absolutely breathtaking visuals. The combat is fluid and the mythology is deep.", date: '2h ago', likes: 124, commentsCount: 18 },
  { id: 'r2', gameId: 'p2', userId: 'user-3', userName: 'AstroViking_TV', userAvatar: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?q=80&w=150&h=150&fit=crop', rating: 5, content: "FOR DEMOCRACY! The best co-op experience of the year by far.", date: '5h ago', likes: 89, commentsCount: 12 },
  { id: 'r3', gameId: 'extra-9', userId: 'user-4', userName: 'PixelHunter_99', userAvatar: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=150&h=150&fit=crop', rating: 5, content: "Infinite possibilities. I've built entire cities in this game. A classic that never gets old.", date: '1d ago', likes: 450, commentsCount: 67 },
  { id: 'r4', gameId: 'extra-13', userId: 'user-5', userName: 'FragLord_zZ', userAvatar: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?q=80&w=150&h=150&fit=crop', rating: 4, content: "Black Ops 6 feels like a return to form. The movement is crisp and the campaign is wild.", date: '3h ago', likes: 320, commentsCount: 45 },
  { id: 'r5', gameId: 'extra-30', userId: 'user-6', userName: 'Valkyrie_Rage', userAvatar: 'https://images.unsplash.com/photo-1614036417651-efe5912149d8?q=80&w=150&h=150&fit=crop', rating: 5, content: "The best pirate game ever made. The ship combat and exploration are still unmatched.", date: '1w ago', likes: 1200, commentsCount: 156 },
  { id: 'r6', gameId: 'extra-16', userId: 'user-7', userName: 'GhostGamer_ITA', userAvatar: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=150&h=150&fit=crop', rating: 5, content: "Rocksteady's masterpiece. The Batmobile is a beast and Gotham has never looked better.", date: '2d ago', likes: 85, commentsCount: 10 }
];

import { HelpRequest } from './types';
export const MOCK_HELP_REQUESTS: HelpRequest[] = [
  { id: 'h1', gameId: 'p1', userId: 'user-2', userName: 'ViperNeon_X', userAvatar: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=150&h=150&fit=crop', timestamp: '10m ago' },
  { id: 'h2', gameId: 'p1', userId: 'user-3', userName: 'AstroViking_TV', userAvatar: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?q=80&w=150&h=150&fit=crop', timestamp: '25m ago' },
  { id: 'h3', gameId: 'p2', userId: 'user-4', userName: 'PixelHunter_99', userAvatar: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=150&h=150&fit=crop', timestamp: '5m ago' },
];
